# -*- coding: utf-8 -*-
"""Coursera Final Assignement

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zRFaPvkhzjkICjZV_sl9wih6Z511FRyf
"""

# My data science notebook

## Welcome to this notebook on data science! In this notebook, we'll explore various aspects of data science and its related languages and libraries.

## python, R, Julia, sql

## NumPy,pandas, Matplotlib, Seaborn,Scikit-Learn, TensorFlow, PyTorch

# Tool                | Description                             |

 #Python              | A versatile programming language often used in data science. |
 #Jupyter Notebook    | An interactive computing environment for data analysis and visualization. |
 #Pandas              | A powerful library for data manipulation and analysis. |
 #NumPy               | A fundamental package for scientific computing with Python. |
 #Scikit-Learn        | A machine learning library for various data science tasks. |
#Matplotlib          | A popular data visualization library. |
 #TensorFlow          | An open-source machine learning framework. |
 #PyTorch             | An open-source deep learning framework. |
 #R                   | A programming language for statistical analysis and data visualization. |
 #Tableau            | A data visualization tool for creating interactive and shareable dashboards. |

## In this section, we'll explore various arithmetic expression examples to demonstrate basic mathematical operations such as addition, subtraction, multiplication, and division in Python.

# Multiplication example
result_multiply = 5 * 3
print("Multiplication Result:", result_multiply)

# Addition example
result_add = 5 + 3
print("Addition Result:", result_add)

# Convert minutes to hours
minutes = 120
hours = minutes / 60
print(f"{minutes} minutes is equal to {hours} hours.")

## Objectives

#1. Introduce commonly used data science tools.
#2. Demonstrate arithmetic expression examples in Python.
#3. Perform basic mathematical operations (multiplication and addition).
#4. Convert minutes to hours.
#5. Share the notebook on GitHub.
#6. Capture a screenshot of the first page of the notebook.

# Author: [Ratan Priya Singh]